language: node_js
node_js:
  - "6.10.3"
cache:
  directories:
    - node_modules
addons:
  sauce_connect: true

script: npm run test && npm run sauce

before_script:
  - npm run test-support-server &
